version: 2
jobs:
  build:
    docker:
      - image: python:3.6.4
    working_directory: ~/adventofcode-2015-py
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            pip install coverage
            python -m unittest day01_test.py -v
            coverage run day01_test.py -v
            coverage report -m
            python -m unittest day13_test.py -v
            coverage run day13_test.py -v
            coverage report -m
            python -m unittest day16_test.py -v
            coverage run day16_test.py -v
            coverage report -m
            python -m unittest day17_test.py -v
            coverage run day17_test.py -v
            coverage report -m
      - run:
          name: "Get the results"
          command: |
            python day01.py inputs/day01.txt
            python day09.py inputs/day09.txt
            python day13.py inputs/day13.txt
            python day16.py inputs/day16.txt
            python day17.py inputs/day17.txt
            python day22.py 50 500 51 9