version: 2
jobs:
  build:
    docker:
      - image: python:2.7.14
    working_directory: ~/adventofcode-2015-py
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            pip install coverage
            python day01_test.py
            coverage run day01.py
            coverage report -m
      - run:
          name: "Get the results"
          command: |
            python day01.py inputs/day01.txt
            python day09.py